package storage

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"gorm.io/gorm"

	"github.com/ivanzzeth/remote-signer/internal/core/types"
)

// SyntheticBudgetRuleID returns the rule_id used by SimulationBudgetRule budgets.
func SyntheticBudgetRuleID(signerAddress string) types.RuleID {
	return types.RuleID("sim:" + strings.ToLower(signerAddress))
}

// SyntheticRuleEnsurer backfills rules(id) rows for sim:<signer> budget tracking.
type SyntheticRuleEnsurer interface {
	EnsureSyntheticBudgetRule(ctx context.Context, signerAddress string) error
}

// EnsureSyntheticBudgetRule inserts a disabled placeholder rules row for
// sim:<signer> budget tracking. Simulation budgets intentionally use
// synthetic rule IDs that are not operator-authored rules; the rule_budgets
// table FK requires a matching rules(id) row.
func (r *GormRuleRepository) EnsureSyntheticBudgetRule(ctx context.Context, signerAddress string) error {
	ruleID := SyntheticBudgetRuleID(signerAddress)
	if _, err := r.Get(ctx, ruleID); err == nil {
		return nil
	} else if !types.IsNotFound(err) {
		return fmt.Errorf("lookup synthetic rule: %w", err)
	}

	signer := strings.ToLower(signerAddress)
	rule := &types.Rule{
		ID:            ruleID,
		Name:          "Simulation budget (auto)",
		Description:   "Internal placeholder for simulation-fallback budget rows (sim:<signer>). Not evaluated.",
		Type:          types.RuleTypeSignerRestriction,
		Mode:          types.RuleModeWhitelist,
		Source:        types.RuleSourceAutoGenerated,
		SignerAddress: &signer,
		Owner:         "system",
		Enabled:       false,
		Priority:      1_000_000,
		Config:        []byte("{}"),
	}
	if err := r.Create(ctx, rule); err != nil {
		if _, getErr := r.Get(ctx, ruleID); getErr == nil {
			return nil
		}
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return nil
		}
		return fmt.Errorf("create synthetic rule: %w", err)
	}
	return nil
}
