//go:build integration

package storage

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"

	"github.com/ivanzzeth/remote-signer/internal/core/types"
)

func setupBudgetFKTestDB(t *testing.T) (*gorm.DB, *GormRuleRepository, *GormBudgetRepository) {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	require.NoError(t, err)
	require.NoError(t, db.Exec("PRAGMA foreign_keys = ON").Error)
	require.NoError(t, db.AutoMigrate(&types.Rule{}, &types.RuleBudget{}))

	fks := []fkSpec{{table: "rule_budgets", col: "rule_id", ref: "rules(id)", onDel: "CASCADE"}}
	require.NoError(t, ensureTableFKs(db, "rule_budgets", fks))

	ruleRepo, err := NewGormRuleRepository(db)
	require.NoError(t, err)
	budgetRepo, err := NewGormBudgetRepository(db)
	require.NoError(t, err)
	return db, ruleRepo, budgetRepo
}

func TestEnsureSyntheticBudgetRule_AllowsBudgetInsertWithFK(t *testing.T) {
	_, ruleRepo, budgetRepo := setupBudgetFKTestDB(t)
	ctx := context.Background()
	signer := "0x0000000000000000000000000000000000000001"
	ruleID := SyntheticBudgetRuleID(signer)

	err := ruleRepo.EnsureSyntheticBudgetRule(ctx, signer)
	require.NoError(t, err)

	stored, err := ruleRepo.Get(ctx, ruleID)
	require.NoError(t, err)
	assert.False(t, stored.Enabled)
	assert.Equal(t, types.RuleSourceAutoGenerated, stored.Source)

	budget := &types.RuleBudget{
		ID:       types.BudgetID(ruleID, "56:native"),
		RuleID:   ruleID,
		Unit:     "56:native",
		MaxTotal: "1000000000000000",
		MaxPerTx: "1000000000000000",
		AlertPct: 80,
	}
	require.NoError(t, budgetRepo.Create(ctx, budget))
}

func TestEnsureSyntheticBudgetRule_Idempotent(t *testing.T) {
	_, ruleRepo, _ := setupBudgetFKTestDB(t)
	ctx := context.Background()
	signer := "0xAbCdEf0000000000000000000000000000000001"

	require.NoError(t, ruleRepo.EnsureSyntheticBudgetRule(ctx, signer))
	require.NoError(t, ruleRepo.EnsureSyntheticBudgetRule(ctx, signer))

	got, err := ruleRepo.Get(ctx, SyntheticBudgetRuleID(signer))
	require.NoError(t, err)
	assert.Equal(t, "sim:0xabcdef0000000000000000000000000000000001", string(got.ID))
}
