// Package validate provides shared input validation for API, config, and chain layer.
// Use for request/query/body and config fields that are not rule-config specific.
// Rule config shape validation stays in internal/ruleconfig.
package validate

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/ivanzzeth/remote-signer/internal/core/types"
)

var ethAddressRegex = regexp.MustCompile(`^0x[0-9a-fA-F]{40}$`)
var hexDataRegex = regexp.MustCompile(`^0x([0-9a-fA-F]{2})*$`)
var hexValueRegex = regexp.MustCompile(`^0x[0-9a-fA-F]+$`)
var chainIDRegex = regexp.MustCompile(`^[1-9][0-9]*$`)

// IsValidEthereumAddress returns true if s is a valid 0x-prefixed 40-char hex address.
func IsValidEthereumAddress(s string) bool {
	return ethAddressRegex.MatchString(s)
}

// IsValidHexData returns true if s is valid 0x-prefixed hex calldata (even number of hex chars).
func IsValidHexData(s string) bool {
	if s == "" || s == "0x" {
		return true // empty calldata is valid
	}
	return hexDataRegex.MatchString(s)
}

// IsValidHexValue returns true if s is a valid 0x-prefixed hex integer (e.g. "0x0", "0x1a2b").
func IsValidHexValue(s string) bool {
	if s == "" || s == "0x0" {
		return true
	}
	return hexValueRegex.MatchString(s)
}

// IsValidChainID returns true if s is a positive decimal integer chain ID.
func IsValidChainID(s string) bool {
	return chainIDRegex.MatchString(s)
}

// IsValidNumericValue returns true if s is a valid numeric value (decimal or 0x hex).
// Accepts: "0", "123456", "0x1a2b", "0x0". Used for gas, value, nonce fields.
func IsValidNumericValue(s string) bool {
	if s == "" || s == "0" || s == "0x0" {
		return true
	}
	if strings.HasPrefix(s, "0x") || strings.HasPrefix(s, "0X") {
		return hexValueRegex.MatchString(s)
	}
	// Decimal
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return len(s) > 0
}

// ValidSignTypes is the set of allowed sign_type values for requests and rule config.
var ValidSignTypes = map[string]bool{
	"personal":    true,
	"typed_data":  true,
	"transaction": true,
	"hash":        true,
	"raw_message": true,
	"eip191":      true,
}

// IsValidWeiDecimal returns true if s is a non-empty string of decimal digits (e.g. max_value/wei).
func IsValidWeiDecimal(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// NormalizeRuleType maps legacy or alias names to the canonical rule type.
func NormalizeRuleType(ruleType string) string {
	switch ruleType {
	case "evm_address_whitelist":
		return string(types.RuleTypeEVMAddressList)
	default:
		return ruleType
	}
}

// ValidRuleModes is the set of allowed rule modes (whitelist, blocklist).
var ValidRuleModes = map[types.RuleMode]bool{
	types.RuleModeWhitelist: true,
	types.RuleModeBlocklist: true,
}

// ValidateRuleMode returns an error if mode is not whitelist or blocklist.
func ValidateRuleMode(mode string) error {
	if mode == "" {
		return fmt.Errorf("mode is required")
	}
	if !ValidRuleModes[types.RuleMode(mode)] {
		return fmt.Errorf("mode must be whitelist or blocklist")
	}
	return nil
}

// ValidChainTypes is the set of allowed chain type values.
var ValidChainTypes = map[types.ChainType]bool{
	types.ChainTypeEVM:    true,
	types.ChainTypeSolana: true,
	types.ChainTypeCosmos: true,
}

// ValidRuleTypes is the set of allowed rule types.
var ValidRuleTypes = map[types.RuleType]bool{
	types.RuleTypeSignerRestriction:    true,
	types.RuleTypeChainRestriction:     true,
	types.RuleTypeSignTypeRestriction:  true,
	types.RuleTypeMessagePattern:       true,
	types.RuleTypeEVMAddressList:       true,
	types.RuleTypeEVMContractMethod:   true,
	types.RuleTypeEVMValueLimit:       true,
	types.RuleTypeEVMSolidityExpression: true,
	types.RuleTypeEVMJS:                true,
	types.RuleTypeEVMDynamicBlocklist:  true,
}

// ValidRuleSources is the set of allowed rule source values.
var ValidRuleSources = map[types.RuleSource]bool{
	types.RuleSourceConfig:        true,
	types.RuleSourceAPI:           true,
	types.RuleSourceAutoGenerated: true,
	types.RuleSourceInstance:      true,
}

// ValidAuditEventTypes is the set of allowed audit event_type values.
var ValidAuditEventTypes = map[types.AuditEventType]bool{
	types.AuditEventTypeAuthSuccess:      true,
	types.AuditEventTypeAuthFailure:     true,
	types.AuditEventTypeSignRequest:    true,
	types.AuditEventTypeSignComplete:   true,
	types.AuditEventTypeSignFailed:     true,
	types.AuditEventTypeSignRejected:   true,
	types.AuditEventTypeRuleMatched:    true,
	types.AuditEventTypeApprovalRequest: true,
	types.AuditEventTypeApprovalGranted: true,
	types.AuditEventTypeApprovalDenied:  true,
	types.AuditEventTypeRuleCreated:    true,
	types.AuditEventTypeRuleUpdated:     true,
	types.AuditEventTypeRuleDeleted:     true,
	types.AuditEventTypeRateLimitHit:    true,
	types.AuditEventTypeAPIRequest:      true,
	types.AuditEventTypeConfigReloaded:  true,
	types.AuditEventTypeTemplateSynced:  true,
	types.AuditEventTypeAPIKeySynced:    true,
	types.AuditEventTypeSignerCreated:   true,
	types.AuditEventTypeSignerLocked:    true,
	types.AuditEventTypeSignerUnlocked:  true,
	types.AuditEventTypeHDWalletCreated: true,
	types.AuditEventTypeHDWalletDerived: true,
}

// ValidAuditSeverities is the set of allowed audit severity values.
var ValidAuditSeverities = map[types.AuditSeverity]bool{
	types.AuditSeverityInfo:     true,
	types.AuditSeverityWarning:  true,
	types.AuditSeverityCritical: true,
}

// ValidSignerTypes is the set of allowed signer type values.
var ValidSignerTypes = map[types.SignerType]bool{
	types.SignerTypePrivateKey: true,
	types.SignerTypeKeystore:   true,
	types.SignerTypeHDWallet:   true,
}

// IsValidChainType returns true if s is a known chain type.
func IsValidChainType(s string) bool {
	return ValidChainTypes[types.ChainType(s)]
}

// IsValidRuleType returns true if s is a known rule type (after normalization).
func IsValidRuleType(s string) bool {
	return ValidRuleTypes[types.RuleType(NormalizeRuleType(s))]
}

// IsValidRuleSource returns true if s is a known rule source.
func IsValidRuleSource(s string) bool {
	return ValidRuleSources[types.RuleSource(s)]
}

// IsValidAuditEventType returns true if s is a known audit event type.
func IsValidAuditEventType(s string) bool {
	return ValidAuditEventTypes[types.AuditEventType(s)]
}

// IsValidAuditSeverity returns true if s is a known audit severity.
func IsValidAuditSeverity(s string) bool {
	return ValidAuditSeverities[types.AuditSeverity(s)]
}

// IsValidSignerType returns true if s is a known signer type.
func IsValidSignerType(s string) bool {
	return ValidSignerTypes[types.SignerType(s)]
}
