// Package evm — rule_delete.go handles rule deletion via the API.
// Guards: read-only mode, config-sourced rules, immutable rules, and ownership.
package evm

import (
	"context"
	"fmt"
	"net/http"

	"github.com/ivanzzeth/remote-signer/internal/api/respond"

	"github.com/ivanzzeth/remote-signer/internal/api/middleware"
	"github.com/ivanzzeth/remote-signer/internal/core/types"
	"github.com/ivanzzeth/remote-signer/internal/storage"
)

func (h *RuleHandler) deleteRule(w http.ResponseWriter, r *http.Request, ruleID string) {
	apiKey := middleware.GetAPIKey(r.Context())
	if apiKey == nil {
		respond.Error(w, "unauthorized", http.StatusUnauthorized, h.logger)
		return
	}

	// Fetch rule first for readOnly and source guards
	rule, err := h.ruleRepo.Get(r.Context(), types.RuleID(ruleID))
	if err != nil {
		if types.IsNotFound(err) {
			respond.Error(w, "rule not found", http.StatusNotFound, h.logger)
			return
		}
		h.logger.Error("failed to get rule", "error", err, "rule_id", ruleID)
		respond.Error(w, "failed to get rule", http.StatusInternalServerError, h.logger)
		return
	}

	if h.isReadOnly() {
		respond.Error(w, "rule deletion via API is disabled (security.rules_api_readonly)", http.StatusForbidden, h.logger)
		return
	}
	if rule.Source == types.RuleSourceConfig {
		respond.Error(w, "cannot delete config-sourced rules via API", http.StatusForbidden, h.logger)
		return
	}

	// Synthetic simulation placeholders (sim:0x...) are system-owned internal rows.
	if isSyntheticBudgetRuleID(ruleID) {
		if !apiKey.IsAdmin() && !apiKey.IsDev() {
			respond.Error(w, "permission denied: synthetic simulation rules require admin", http.StatusForbidden, h.logger)
			return
		}
		if rule.Source != types.RuleSourceAutoGenerated {
			respond.Error(w, "cannot delete non-auto-generated synthetic rule", http.StatusForbidden, h.logger)
			return
		}
	}

	// Immutable check
	if rule.Immutable {
		respond.Error(w, "cannot delete immutable rule", http.StatusForbidden, h.logger)
		return
	}

	// Ownership check: only owner or admin can delete
	if !apiKey.IsAdmin() && rule.Owner != apiKey.ID {
		respond.Error(w, "permission denied: can only delete own rules", http.StatusForbidden, h.logger)
		return
	}

	if err := h.deleteRuleAndBudgets(r.Context(), rule.ID); err != nil {
		if types.IsNotFound(err) {
			respond.Error(w, "rule not found", http.StatusNotFound, h.logger)
			return
		}
		h.logger.Error("failed to delete rule", "error", err, "rule_id", ruleID)
		respond.Error(w, "failed to delete rule", http.StatusInternalServerError, h.logger)
		return
	}

	h.logger.Info("rule deleted", "rule_id", ruleID)
	if h.auditLogger != nil {
		clientIP, _ := r.Context().Value(middleware.ClientIPContextKey).(string)
		h.auditLogger.LogRuleDeleted(r.Context(), apiKey.ID, clientIP, rule.ID)
	}
	w.WriteHeader(http.StatusNoContent)
}

// deleteRuleAndBudgets removes a rule and all associated budgets atomically
// when the rule repository supports RuleBudgetTransactional (GORM/SQLite).
// Budgets are deleted before the rule so orphaned budget rows cannot linger
// when foreign-key CASCADE is missing or disabled.
func (h *RuleHandler) deleteRuleAndBudgets(ctx context.Context, ruleID types.RuleID) error {
	if h.budgetRepo == nil {
		return h.ruleRepo.Delete(ctx, ruleID)
	}

	if txRepo, ok := h.ruleRepo.(storage.RuleBudgetTransactional); ok {
		return txRepo.RunInRuleBudgetTransaction(ctx, func(txRule storage.RuleRepository, txBudget storage.BudgetRepository) error {
			if err := txBudget.DeleteByRuleID(ctx, ruleID); err != nil {
				return fmt.Errorf("delete rule budgets: %w", err)
			}
			if err := txRule.Delete(ctx, ruleID); err != nil {
				return fmt.Errorf("delete rule: %w", err)
			}
			return nil
		})
	}

	if err := h.budgetRepo.DeleteByRuleID(ctx, ruleID); err != nil {
		return fmt.Errorf("delete rule budgets: %w", err)
	}
	return h.ruleRepo.Delete(ctx, ruleID)
}
