package rule

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ivanzzeth/remote-signer/internal/core/types"
)

// ─────────────────────────────────────────────────────────────────────────────
// RuleGenerateOptions.Validate
// ─────────────────────────────────────────────────────────────────────────────

func TestRuleGenerateOptions_Validate(t *testing.T) {
	maxVal := "1000"

	tests := []struct {
		name    string
		opts    RuleGenerateOptions
		wantErr string
	}{
		{"missing rule_type", RuleGenerateOptions{RuleMode: types.RuleModeWhitelist}, "rule_type is required"},
		{"missing rule_mode", RuleGenerateOptions{RuleType: types.RuleTypeEVMAddressList}, "rule_mode is required"},
		{"invalid rule_mode", RuleGenerateOptions{RuleType: types.RuleTypeEVMAddressList, RuleMode: "invalid"}, "must be 'whitelist' or 'blocklist'"},
		{"unsupported rule_type", RuleGenerateOptions{RuleType: "evm_js", RuleMode: types.RuleModeWhitelist}, "unsupported rule_type"},
		{"address_list valid", RuleGenerateOptions{RuleType: types.RuleTypeEVMAddressList, RuleMode: types.RuleModeWhitelist}, ""},
		{"contract_method valid", RuleGenerateOptions{RuleType: types.RuleTypeEVMContractMethod, RuleMode: types.RuleModeWhitelist}, ""},
		{"value_limit missing max_value", RuleGenerateOptions{RuleType: types.RuleTypeEVMValueLimit, RuleMode: types.RuleModeWhitelist}, "max_value is required"},
		{"value_limit valid", RuleGenerateOptions{RuleType: types.RuleTypeEVMValueLimit, RuleMode: types.RuleModeWhitelist, MaxValue: &maxVal}, ""},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			err := tc.opts.Validate()
			if tc.wantErr != "" {
				assert.Error(t, err)
				assert.Contains(t, err.Error(), tc.wantErr)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// NewDefaultRuleGenerator
// ─────────────────────────────────────────────────────────────────────────────

func TestNewDefaultRuleGenerator(t *testing.T) {
	gen, err := NewDefaultRuleGenerator()
	require.NoError(t, err)
	assert.NotNil(t, gen)
}

// ─────────────────────────────────────────────────────────────────────────────
// SupportedTypes
// ─────────────────────────────────────────────────────────────────────────────

func TestDefaultRuleGenerator_SupportedTypes(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()
	supported := gen.SupportedTypes()
	assert.Len(t, supported, 3)
	assert.Contains(t, supported, types.RuleTypeEVMAddressList)
	assert.Contains(t, supported, types.RuleTypeEVMContractMethod)
	assert.Contains(t, supported, types.RuleTypeEVMValueLimit)
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: address list
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_AddressList_Whitelist(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	recipient := "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Recipient: &recipient}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeWhitelist,
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)
	assert.Equal(t, types.RuleTypeEVMAddressList, rule.Type)
	assert.Equal(t, types.RuleModeWhitelist, rule.Mode)
	assert.Equal(t, types.RuleSourceAutoGenerated, rule.Source)
	assert.True(t, rule.Enabled)
	assert.Contains(t, rule.Name, "Allow:")
	assert.Contains(t, rule.Name, recipient)
	assert.NotEmpty(t, rule.Config)

	// Verify config
	var cfg addressListConfig
	require.NoError(t, json.Unmarshal(rule.Config, &cfg))
	assert.Equal(t, []string{recipient}, cfg.Addresses)

	// Rule ID is not prefixed with "preview_"
	assert.False(t, strings.HasPrefix(string(rule.ID), "preview_"))
}

func TestGenerate_AddressList_Blocklist(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	recipient := "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Recipient: &recipient}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeBlocklist,
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)
	assert.Contains(t, rule.Name, "Block:")
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: contract method
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_ContractMethod(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	contract := "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
	method := "0xa9059cbb"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Contract: &contract, MethodSig: &method}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMContractMethod,
		RuleMode: types.RuleModeWhitelist,
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)

	var cfg contractMethodConfig
	require.NoError(t, json.Unmarshal(rule.Config, &cfg))
	assert.Equal(t, contract, cfg.Contract)
	assert.Equal(t, []string{method}, cfg.MethodSigs)
}

func TestGenerate_ContractMethod_MissingData(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMContractMethod,
		RuleMode: types.RuleModeWhitelist,
	}

	// nil parsed
	_, err := gen.Generate(req, nil, opts)
	assert.Error(t, err)

	// nil contract
	method := "0xa9059cbb"
	_, err = gen.Generate(req, &types.ParsedPayload{MethodSig: &method}, opts)
	assert.Error(t, err)

	// nil method_sig
	contract := "0xabc"
	_, err = gen.Generate(req, &types.ParsedPayload{Contract: &contract}, opts)
	assert.Error(t, err)
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: value limit
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_ValueLimit(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	maxVal := "1000000000000000000"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMValueLimit,
		RuleMode: types.RuleModeBlocklist,
		MaxValue: &maxVal,
	}

	rule, err := gen.Generate(req, nil, opts)
	require.NoError(t, err)

	var cfg valueLimitConfig
	require.NoError(t, json.Unmarshal(rule.Config, &cfg))
	assert.Equal(t, maxVal, cfg.MaxValue)
	assert.Contains(t, rule.Name, "Block:")
}

func TestGenerate_ContractMethod_Blocklist(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	contract := "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
	method := "0xa9059cbb"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Contract: &contract, MethodSig: &method}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMContractMethod,
		RuleMode: types.RuleModeBlocklist,
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)
	assert.Contains(t, rule.Name, "Block:")
	assert.Contains(t, rule.Name, method)
	assert.Contains(t, rule.Name, contract)
}

func TestGenerate_ValueLimit_Whitelist(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	maxVal := "1000000000000000000"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMValueLimit,
		RuleMode: types.RuleModeWhitelist,
		MaxValue: &maxVal,
	}

	rule, err := gen.Generate(req, nil, opts)
	require.NoError(t, err)
	assert.Contains(t, rule.Name, "Allow:")
}

// ─────────────────────────────────────────────────────────────────────────────
// Preview: prefixed ID
// ─────────────────────────────────────────────────────────────────────────────

func TestPreview_PrefixedID(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	recipient := "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Recipient: &recipient}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeWhitelist,
	}

	rule, err := gen.Preview(req, parsed, opts)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(rule.ID), "preview_"))
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: custom name
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_CustomName(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	recipient := "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Recipient: &recipient}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeWhitelist,
		RuleName: "My Custom Rule",
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)
	assert.Equal(t, "My Custom Rule", rule.Name)
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: nil request
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_NilRequest(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeWhitelist,
	}

	_, err := gen.Generate(nil, nil, opts)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "request is required")
}

func TestGenerate_NilOptions(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "1",
		APIKeyID:      "key-1",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}

	_, err := gen.Generate(req, nil, nil)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "options are required")
}

// ─────────────────────────────────────────────────────────────────────────────
// Generate: scope fields propagated
// ─────────────────────────────────────────────────────────────────────────────

func TestGenerate_ScopeFieldsPropagated(t *testing.T) {
	gen, _ := NewDefaultRuleGenerator()

	recipient := "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"
	req := &types.SignRequest{
		ID:            "req-1",
		ChainType:     types.ChainTypeEVM,
		ChainID:       "137",
		APIKeyID:      "api-key-42",
		SignerAddress: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
	}
	parsed := &types.ParsedPayload{Recipient: &recipient}
	opts := &RuleGenerateOptions{
		RuleType: types.RuleTypeEVMAddressList,
		RuleMode: types.RuleModeWhitelist,
	}

	rule, err := gen.Generate(req, parsed, opts)
	require.NoError(t, err)
	require.NotNil(t, rule.ChainType)
	assert.Equal(t, types.ChainTypeEVM, *rule.ChainType)
	require.NotNil(t, rule.ChainID)
	assert.Equal(t, "137", *rule.ChainID)
	require.NotNil(t, rule.APIKeyID)
	assert.Equal(t, "api-key-42", *rule.APIKeyID)
	require.NotNil(t, rule.SignerAddress)
	assert.Equal(t, "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", *rule.SignerAddress)
}
