package types

import "time"

// RuleID is a unique identifier for rules
type RuleID string

// RuleType represents the type of rule
type RuleType string

const (
	// Chain-agnostic rule types
	RuleTypeSignerRestriction   RuleType = "signer_restriction"
	RuleTypeChainRestriction    RuleType = "chain_restriction"
	RuleTypeSignTypeRestriction RuleType = "sign_type_restriction"
	RuleTypeMessagePattern      RuleType = "message_pattern" // regex pattern matching for personal sign messages

	// EVM-specific rule types (prefixed)
	// Mode (whitelist/blocklist) determines behavior, not the type name
	RuleTypeEVMAddressList         RuleType = "evm_address_list"         // address list (whitelist mode = allow, blocklist mode = block)
	RuleTypeEVMContractMethod      RuleType = "evm_contract_method"      // contract method restriction
	RuleTypeEVMValueLimit          RuleType = "evm_value_limit"          // value limit check
	RuleTypeEVMSolidityExpression  RuleType = "evm_solidity_expression"  // Solidity expression rules (Foundry-based)
	RuleTypeEVMJS                  RuleType = "evm_js"                    // JS rules (in-process Sobek); validate(input) → { valid, reason?, payload? }
)

// RuleSource represents where the rule came from
type RuleSource string

const (
	RuleSourceConfig        RuleSource = "config"
	RuleSourceAPI           RuleSource = "api"
	RuleSourceAutoGenerated RuleSource = "auto_generated"
	RuleSourceInstance      RuleSource = "instance" // created from template
)

// RuleMode represents how the rule is evaluated
type RuleMode string

const (
	// RuleModeWhitelist - ANY match = allow (permissive)
	// Used for: address whitelist, contract method whitelist
	RuleModeWhitelist RuleMode = "whitelist"

	// RuleModeBlocklist - ANY violation = block immediately (restrictive)
	// Used for: value limits, rate limits, global restrictions
	// Blocklist rules are evaluated BEFORE whitelist rules
	// If ANY blocklist rule is violated, request is rejected (no manual approval)
	RuleModeBlocklist RuleMode = "blocklist"
)

// Rule represents a signing authorization rule
type Rule struct {
	ID          RuleID     `json:"id" gorm:"primaryKey;type:varchar(64)"`
	Name        string     `json:"name" gorm:"type:varchar(255)"`
	Description string     `json:"description,omitempty" gorm:"type:text"`
	Type        RuleType   `json:"type" gorm:"index;type:varchar(64)"`
	Mode        RuleMode   `json:"mode" gorm:"index;type:varchar(16);default:'whitelist'"` // whitelist or blocklist
	Source      RuleSource `json:"source" gorm:"type:varchar(32)"`

	// Scope
	ChainType     *ChainType `json:"chain_type,omitempty" gorm:"index;type:varchar(32)"` // nil = all chains
	ChainID       *string    `json:"chain_id,omitempty" gorm:"type:varchar(32)"`
	APIKeyID      *string    `json:"api_key_id,omitempty" gorm:"index;type:varchar(64)"`
	SignerAddress *string    `json:"signer_address,omitempty" gorm:"index;type:varchar(128)"`

	// Chain-specific config stored as JSON
	Config []byte `json:"config" gorm:"type:jsonb"`

	// Template instance fields (nullable, backward compatible)
	TemplateID *string `json:"template_id,omitempty" gorm:"type:varchar(128)"`
	Variables  []byte  `json:"variables,omitempty" gorm:"type:jsonb"` // map[string]string — bound variable values

	// Schedule fields — for periodic budget renewal
	// When BudgetPeriod is set, the instance automatically renews its budget
	// at each period boundary. ExpiresAt still controls the overall lifetime.
	BudgetPeriod      *time.Duration `json:"budget_period,omitempty" gorm:"type:bigint"`         // e.g. 24h, 7*24h
	BudgetPeriodStart *time.Time     `json:"budget_period_start,omitempty" gorm:"type:datetime"` // when the first period begins (datetime for SQLite compat)

	Enabled   bool       `json:"enabled" gorm:"index"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	MatchCount    uint64     `json:"match_count"`
	LastMatchedAt *time.Time `json:"last_matched_at,omitempty"`
}

// TableName specifies the table name for GORM
func (Rule) TableName() string {
	return "rules"
}

// RuleEvaluationResult represents the result of rule evaluation
type RuleEvaluationResult struct {
	RuleID      RuleID    `json:"rule_id"`
	Matched     bool      `json:"matched"`
	Reason      string    `json:"reason,omitempty"`
	EvaluatedAt time.Time `json:"evaluated_at"`
}
